#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "jellybeans"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    # File tree options
    filetree_direction = "left"
    enable_filetree_gitstatus = true

    relativenumber = false

    # it breaks in multiple things like yocto layers
    project_rooter_outermost = false

    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

[[custom_plugins]]
    repo = 'kergoth/vim-bitbake'

[[custom_plugins]]
    repo = 'cdaddr/gentooish.vim'

[[custom_plugins]]
    repo = 'mattesgroeger/vim-bookmarks'

[[custom_plugins]]
    repo = 'wgwoods/vim-systemd-syntax'

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'git'
    git_plugin = 'fugitive'

[[layers]]
    name = 'VersionControl'

[[layers]]
    name = 'lsp'
    enabled_clients = ['vimls']

[[layers]]
    name = 'treesitter'

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "ctrlp"
